//! [![Crates.io Version](https://img.shields.io/crates/v/breaking-attr)](https://crates.io/crates/breaking-attr)
//! [![docs.rs](https://img.shields.io/docsrs/breaking-attr)](https://docs.rs/breaking-attr)
//! [![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/Waridley/breaking-attr/.github%2Fworkflows%2Fci.yml)](https://github.com/Waridley/breaking-attr/actions)
//!
//! An attribute macro that enforces per-version invariants on items.
//!
//! ```
//! use breaking_attr::breaking;
//!
//! # use blake3::{hash, Hash};
//!
//! #[cfg_attr(test, test)]
//! fn hash_impl_did_not_change() {
//!     #[breaking(sha2 = "zEk8F98i1LX-Rr070lCztGerzO1-qlLbosetY1UvSww=")]
//!     const SEED: &str = "This value must not change between minor versions.";
//!     #[breaking("ipCxMeWK-ImjLQVZX7YQXqjguSC5jOc5oCexXl5Bw0g=")] // Hasher defaults to `blake3`
//!     const HASH: &[u8] = &[89, 216, 231, 42, 61, 80, 228, 91, 200, 17, 218, 190, 61, 187, 1, 13, 90, 195, 84, 57, 249, 109, 90, 79, 175, 103, 37, 195, 98, 32, 157, 102];
//!
//!     let hash = hash(SEED.as_bytes());
//!     debug_assert_eq!(hash.as_bytes(), HASH);
//! }
//!
//! # hash_impl_did_not_change()
//! ```
//!
//! See the documentation on [`breaking`](`macro@breaking`)

use base64::{Engine, engine::general_purpose::URL_SAFE as BASE_64};
use proc_macro::TokenStream;
use proc_macro2::{Span, TokenTree};
use syn::__private::ToTokens;
use syn::{Ident, LitStr, Token, punctuated::Punctuated};

#[cfg(not(any(feature = "blake3", feature = "sha2", feature = "md5",)))]
compile_error!("At least one hasher feature must be enabled");

/// Marks an item that will break the public API if it is changed.
///
/// This attribute takes a single argument, which must be a string literal of the url-safe base64-
/// encoded hash of the token stream of the item marked by this attribute.
///
/// Changes to items marked with this attribute require updating the hash argument (which can be
/// retrieved from the compile error generated by running it with a wrong hash) and most likely
/// bumping the major version of the crate containing the item. At the very least, it must be
/// explained in the commit message and any accompanying PR why the hash was updated without bumping
/// the major version.
///
/// ### Hashers
/// Multiple hash functions are supported via feature flags.
///
/// - [`blake3`] (default)
/// - With the `sha2` dependency
///   - [`sha256`](`sha2::Sha256`) (also aliased to `sha2`)
///   - [`sha224`](`sha2::Sha224`)
///   - [`sha384`](`sha2::Sha384`)
///   - [`sha512`](`sha2::Sha512`)
///   - [`sha512_224`](`sha2::Sha512_224`)
///   - [`sha512_256`](`sha2::Sha512_256`)
/// - [`md5`]
///
/// ```
/// use breaking_attr::breaking;
///
/// # #[cfg(feature = "sha2")]
/// #[breaking(sha384 = "82y9Notlejn-Nfzl4SurR3m3Uqeaqt0jmN-wGHSAjNkHeywz1zYZeUJi-5-D0wo3")]
/// const SHA_384: &str = "This string must not change without updating the hash.";
///
/// # #[cfg(feature = "blake3")]
/// #[breaking("IjrbZ-YsIRSb2v3ELtz-4zMqGvu5FVCkwotqCKMdhDE=")]
/// const DEFAULT: &str = "The default hasher is `blake3`";
/// ```
#[proc_macro_attribute]
pub fn breaking(args: TokenStream, input: TokenStream) -> TokenStream {
    let args =
        syn::parse_macro_input!(args with Punctuated::<TokenTree, Token![=]>::parse_terminated);

    let Some(expected) = args.iter().find_map(|arg| {
        let TokenTree::Literal(lit) = arg else {
            return None;
        };
        syn::parse::<LitStr>(lit.to_token_stream().into()).ok()
    }) else {
        let msg = "couldn't find string literal of hash in arguments";
        let err = syn::Error::new(Span::call_site(), msg);
        return err.into_compile_error().into();
    };
    let expected = expected.value();

    let hasher = args.iter().find_map(|arg| {
        let TokenTree::Ident(ident) = arg else {
            return None;
        };
        Some(ident)
    });
    let input_str = input.to_string();
    #[cfg(not(all(feature = "blake3", feature = "sha2", feature = "md5",)))]
    let feature_error = |feature: &str| {
        let msg = format!(
            "either the `{feature}` feature must be enabled or a different hasher must be specified"
        );
        let err = syn::Error::new_spanned(hasher.unwrap(), msg);
        TokenStream::from(err.into_compile_error())
    };
    let hash = match hasher.map(Ident::to_string).as_deref() {
        None | Some("blake3") => {
            #[cfg(feature = "blake3")]
            {
                blake3::hash(input_str.as_bytes()).as_bytes().to_vec()
            }
            #[cfg(not(feature = "blake3"))]
            return feature_error("blake3");
        }
        Some(s) if s.starts_with("sha") => {
            #[cfg(feature = "sha2")]
            {
                use sha2::Digest;
                fn sha2(input: &str, mut hasher: impl Digest) -> Vec<u8> {
                    hasher.update(input.as_bytes());
                    hasher.finalize().to_vec()
                }
                match s {
                    "sha2" | "sha256" => sha2(&input_str, sha2::Sha256::new()),
                    "sha224" => sha2(&input_str, sha2::Sha224::new()),
                    "sha384" => sha2(&input_str, sha2::Sha384::new()),
                    "sha512" => sha2(&input_str, sha2::Sha512::new()),
                    "sha512_224" => sha2(&input_str, sha2::Sha512_224::new()),
                    "sha512_256" => sha2(&input_str, sha2::Sha512_256::new()),
                    _ => {
                        return syn::Error::new_spanned(
                            hasher.unwrap(),
                            "unrecognized sha version",
                        )
                        .into_compile_error()
                        .into();
                    }
                }
            }
            #[cfg(not(feature = "sha2"))]
            return feature_error("sha2");
        }
        Some("md5") => {
            #[cfg(feature = "md5")]
            {
                md5::compute(input_str.as_bytes()).0.to_vec()
            }
            #[cfg(not(feature = "md5"))]
            return feature_error("md5");
        }
        Some(other) => {
            let msg = format!("unrecognized hasher `{other}`");
            return syn::Error::new_spanned(hasher.unwrap(), msg)
                .into_compile_error()
                .into();
        }
    };
    let hash = BASE_64.encode(hash);
    if hash != expected {
        let msg = format!("hash {hash:?} doesn't match");
        return syn::Error::new(proc_macro::Span::call_site().into(), msg)
            .into_compile_error()
            .into();
    }
    input
}
